// File generated by FlutterFire CLI.
// This is a placeholder file. Follow the setup instructions in SETUP.md
// to configure Firebase properly using: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0_2SrTQSgYHOqLwuXWOHAApV1DMp7vMY',
    appId: '1:380579261695:web:b3ad480f2290e85701f0ca',
    messagingSenderId: '380579261695',
    projectId: 'productpulse-app',
    authDomain: 'productpulse-app.firebaseapp.com',
    storageBucket: 'productpulse-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqEC-HX9lIxdccvxe_S5gzOrztq_2uAXE',
    appId: '1:380579261695:android:96d7c2073e08aa6501f0ca',
    messagingSenderId: '380579261695',
    projectId: 'productpulse-app',
    storageBucket: 'productpulse-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXJ_dteuWtYMeuB12UYLxuH8NxMtXnsCM',
    appId: '1:380579261695:ios:14fd26aae898763201f0ca',
    messagingSenderId: '380579261695',
    projectId: 'productpulse-app',
    storageBucket: 'productpulse-app.firebasestorage.app',
    iosBundleId: 'com.example.productpulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXJ_dteuWtYMeuB12UYLxuH8NxMtXnsCM',
    appId: '1:380579261695:ios:14fd26aae898763201f0ca',
    messagingSenderId: '380579261695',
    projectId: 'productpulse-app',
    storageBucket: 'productpulse-app.firebasestorage.app',
    iosBundleId: 'com.example.productpulse',
  );

}